spring:
  application:
    name: choosethename-backend
  datasource:
    url: ${BDD_URL}
    username: ${BDD_USERNAME}
    password: ${BDD_PASSWORD}
    driver-class-name: ${BDD_DRIVER}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: REDACTED
  expiration-ms: 86400000
