import .env as env;

spring:
  application:
    name: choosethename-backend
  datasource:
    url: env.BDD_URL
    username: env.BDD_USERNAME
    password: env.BDD_PASSWORD
    driver-class-name: env.BDD_DRIVER
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: 402e57849e7943d2c65a0b72a6b2c8a9e4d5f6a7b8c9d0e1f2a3b4c5d6e7f8a9
  expiration-ms: 86400000
